# Generated by Django 4.2 on 2024-04-05 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名字')),
                ('topic', models.CharField(max_length=20, unique=True, verbose_name='主题')),
                ('category', models.CharField(choices=[('light', '灯'), ('switch', '插座'), ('fan', '风扇'), ('window', '窗户'), ('curtain', '窗帘'), ('sensor', '传感器')], max_length=10, verbose_name='类别')),
                ('position', models.CharField(choices=[('bedroom', '卧室'), ('livingroom', '客厅'), ('kitchen', '厨房')], max_length=10, verbose_name='位置')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate', models.CharField(max_length=50, verbose_name='操作')),
                ('status', models.CharField(choices=[('on', '开'), ('off', '关')], max_length=5, verbose_name='状态')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '窗户',
                'verbose_name_plural': '窗户',
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate', models.CharField(max_length=50, verbose_name='操作')),
                ('status', models.CharField(choices=[('on', '开'), ('off', '关')], max_length=5, verbose_name='状态')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '插座',
                'verbose_name_plural': '插座',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '温湿度传感器',
                'verbose_name_plural': '温湿度传感器',
            },
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate', models.CharField(max_length=50, verbose_name='操作')),
                ('status', models.CharField(choices=[('on', '开'), ('off', '关')], max_length=5, verbose_name='状态')),
                ('lightness', models.IntegerField(blank=True, null=True, verbose_name='亮度')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='颜色')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '灯',
                'verbose_name_plural': '灯',
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate', models.CharField(max_length=50, verbose_name='操作')),
                ('status', models.CharField(choices=[('on', '开'), ('one', '一档'), ('two', '二档'), ('three', '三档'), ('four', '四档'), ('off', '关')], max_length=5, verbose_name='状态')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '风扇',
                'verbose_name_plural': '风扇',
            },
        ),
        migrations.CreateModel(
            name='Curtain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate', models.CharField(max_length=50, verbose_name='操作')),
                ('status', models.CharField(choices=[('on', '开'), ('off', '关'), ('pause', '暂停')], max_length=5, verbose_name='状态')),
                ('schedule', models.IntegerField(blank=True, null=True, verbose_name='进度')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '窗帘',
                'verbose_name_plural': '窗帘',
            },
        ),
    ]
