# Generated by Django 4.2 on 2024-05-23 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='home.device', verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device', verbose_name='传感器'),
        ),
    ]
