# Generated by Django 4.2 on 2024-04-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='add_time',
        ),
    ]
